# Generated by Django 5.1 on 2026-09-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_collections', '0002_bureauinvoice_bureauinvoiceline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bureauinvoiceline',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='bureauinvoiceline',
            name='payment',
        ),
        migrations.DeleteModel(
            name='BureauInvoice',
        ),
        migrations.DeleteModel(
            name='BureauInvoiceLine',
        ),
    ]
