# Generated by Django 5.1 on 2026-09-11 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice_name', models.CharField(max_length=255)),
                ('bhf_practice_number', models.CharField(help_text='Board of Healthcare Funders practice number', max_length=20, unique=True)),
                ('hpcsa_number', models.CharField(help_text='HPCSA registration number', max_length=20)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_account_number', models.CharField(blank=True, max_length=30)),
                ('bank_branch_code', models.CharField(blank=True, max_length=10)),
                ('switch_provider', models.CharField(choices=[('mediswitch', 'MediSwitch'), ('healthbridge', 'Healthbridge'), ('medikredit', 'MediKredit'), ('none', 'None')], default='none', max_length=20)),
                ('switch_account_id', models.CharField(blank=True, max_length=50)),
                ('fee_type', models.CharField(choices=[('percentage', 'Percentage of Collections'), ('fixed', 'Fixed Monthly Fee'), ('hybrid', 'Hybrid (Fixed + Percentage)')], default='percentage', max_length=20)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=7.0, help_text='Percentage fee on collected revenue', max_digits=5)),
                ('fee_fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed monthly fee in Rands', max_digits=10)),
                ('popia_agreement_signed_date', models.DateField(blank=True, null=True)),
                ('service_agreement_signed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
                'ordering': ['practice_name'],
            },
        ),
    ]
