# Generated by Django 5.1 on 2026-09-12 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Percentage fee on collected revenue', max_digits=5),
        ),
        migrations.CreateModel(
            name='PortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.CharField(choices=[('discovery', 'Discovery Health Provider Portal'), ('medscheme', 'Medscheme / GEMS Provider Portal'), ('momentum', 'Momentum / Metropolitan Online'), ('universal', 'Universal Healthcare Portal'), ('simulator', 'Direct Portal Simulator (Dry-Run Test)')], max_length=50)),
                ('portal_url', models.URLField(blank=True)),
                ('username', models.CharField(help_text='Practice portal username or practice number', max_length=100)),
                ('password', models.CharField(help_text='Stored password for headless browser login', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_credentials', to='practices.practice')),
            ],
            options={
                'verbose_name': 'Portal Credential',
                'verbose_name_plural': 'Portal Credentials',
                'ordering': ['practice', 'administrator'],
                'unique_together': {('practice', 'administrator')},
            },
        ),
    ]
