# Generated by Django 5.1 on 2026-09-12 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0002_alter_practice_fee_percentage_portalcredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_practices', to=settings.AUTH_USER_MODEL),
        ),
    ]
