# Generated by Django 5.1 on 2026-09-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practices', '0004_alter_portalcredential_id_alter_practice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='bank_branch_code',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='fee_fixed_amount',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='fee_percentage',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='fee_type',
        ),
        migrations.DeleteModel(
            name='PortalCredential',
        ),
    ]
