# Generated by Django 5.1 on 2026-09-12 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('scope', models.CharField(default='default', max_length=100)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('status_code', models.IntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idempotency Record',
                'verbose_name_plural': 'Idempotency Records',
                'indexes': [models.Index(fields=['idempotency_key', 'scope'], name='api_idempot_idempot_a5d15b_idx')],
                'unique_together': {('idempotency_key', 'scope')},
            },
        ),
    ]
