# Generated by Django 5.1 on 2026-09-11 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('practices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_service', models.DateField()),
                ('referring_doctor_bhf', models.CharField(blank=True, max_length=20)),
                ('referring_doctor_name', models.CharField(blank=True, max_length=255)),
                ('authorization_number', models.CharField(blank=True, max_length=50)),
                ('claim_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid in Full'), ('partially_paid', 'Partially Paid'), ('appealed', 'Under Appeal'), ('written_off', 'Written Off')], default='draft', max_length=20)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('switch_reference_number', models.CharField(blank=True, max_length=100)),
                ('total_billed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_patient_liable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Capture'), ('photo', 'Photo/Scan Upload'), ('day_sheet', 'Day Sheet')], default='manual', max_length=20)),
                ('source_file', models.ImageField(blank=True, null=True, upload_to='claim_sources/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='patients.patient')),
                ('patient_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='patients.patientscheme')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='practices.practice')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'ordering': ['-date_of_service', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_code', models.CharField(max_length=20)),
                ('tariff_description', models.CharField(blank=True, max_length=500)),
                ('icd10_primary', models.CharField(max_length=10)),
                ('icd10_secondary', models.CharField(blank=True, max_length=10)),
                ('icd10_tertiary', models.CharField(blank=True, max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('amount_billed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modifier_codes', models.JSONField(blank=True, default=list)),
                ('nappi_code', models.CharField(blank=True, max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_patient_liable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_scheme_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid in Full'), ('short_paid', 'Short Paid'), ('rejected', 'Rejected'), ('appealed', 'Under Appeal')], default='pending', max_length=20)),
                ('rejection_code', models.CharField(blank=True, max_length=20)),
                ('rejection_description', models.CharField(blank=True, max_length=500)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Claim Line Item',
                'verbose_name_plural': 'Claim Line Items',
                'ordering': ['id'],
            },
        ),
    ]
