# Generated by Django 5.1 on 2026-09-12 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_assigned_to_claim_internal_priority_claimnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RpaSubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_name', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='rpa_proofs/%Y/%m/')),
                ('execution_time_seconds', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpa_submissions', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'RPA Submission Log',
                'verbose_name_plural': 'RPA Submission Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
