# Generated by Django 5.1 on 2026-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_rpasubmissionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requires_correction', 'Requires Correction'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('paid', 'Paid in Full'), ('partially_paid', 'Partially Paid'), ('appealed', 'Under Appeal'), ('written_off', 'Written Off')], default='draft', max_length=20),
        ),
    ]
