# Generated by Django 5.1 on 2026-09-12 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claim_claim_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EdiTransmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_reference', models.CharField(db_index=True, max_length=100)),
                ('switch_provider', models.CharField(choices=[('mediswitch', 'MediSwitch'), ('healthbridge', 'Healthbridge'), ('medikredit', 'MediKredit'), ('other', 'Other')], default='mediswitch', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued for Batching'), ('transmitted', 'Transmitted to Switch'), ('accepted', 'Accepted by Clearinghouse'), ('rejected', 'Rejected by Clearinghouse'), ('failed', 'Transmission Failed')], default='transmitted', max_length=20)),
                ('edi_payload', models.TextField(blank=True, help_text='Raw Medclaim EDI file content')),
                ('response_payload', models.TextField(blank=True, help_text='Raw Switch ACK/NAK response')),
                ('error_details', models.TextField(blank=True)),
                ('transmission_timestamp', models.DateTimeField(auto_now_add=True)),
                ('claims_count', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edi_transmissions', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'EDI Transmission Log',
                'verbose_name_plural': 'EDI Transmission Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
