# Generated by Django 5.1 on 2026-09-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claim_id_alter_claimlineitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='internal_priority',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='source_file',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='source_type',
        ),
    ]
