# Generated by Django 5.1 on 2026-09-12 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAidPortalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administrator', models.CharField(choices=[('discovery', 'Discovery Health Provider Portal'), ('medscheme', 'Medscheme / GEMS Provider Portal'), ('momentum', 'Momentum / Metropolitan Online'), ('universal', 'Universal Healthcare Portal'), ('simulator', 'Direct Portal Simulator (Dry-Run Test)')], help_text='South African medical scheme administrator gateway', max_length=50, unique=True)),
                ('username', models.CharField(help_text='Bureau master username or registered portal login ID', max_length=100)),
                ('password', models.CharField(help_text='Bureau portal login password', max_length=255)),
                ('portal_url', models.URLField(blank=True, help_text='Gateway URL for direct headless browser navigation')),
                ('bureau_bhf_number', models.CharField(blank=True, help_text='Bureau BHF accredited registration number (if applicable)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Enable for automated headless claim submission')),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='Untested', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Medical Aid Portal Credential',
                'verbose_name_plural': 'Medical Aid Portal Credentials',
                'ordering': ['administrator'],
            },
        ),
    ]
