# Generated by Django 5.1 on 2026-09-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalaidportalcredential',
            name='circuit_state',
            field=models.CharField(choices=[('closed', 'Healthy / Closed'), ('open', 'Tripped / Open'), ('half_open', 'Probing / Half-Open')], default='closed', help_text='Circuit breaker status for gateway protection', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalaidportalcredential',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive submission or authentication failures'),
        ),
        migrations.AddField(
            model_name='medicalaidportalcredential',
            name='cooldown_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Duration in minutes to pause requests when tripped'),
        ),
        migrations.AddField(
            model_name='medicalaidportalcredential',
            name='failure_threshold',
            field=models.PositiveIntegerField(default=3, help_text='Failures before tripping the circuit breaker'),
        ),
        migrations.AddField(
            model_name='medicalaidportalcredential',
            name='last_failure_reason',
            field=models.TextField(blank=True, help_text='Reason recorded on most recent gateway failure'),
        ),
        migrations.AddField(
            model_name='medicalaidportalcredential',
            name='tripped_until',
            field=models.DateTimeField(blank=True, help_text='Timestamp when cooldown expires', null=True),
        ),
    ]
