# Generated by Django 5.1 on 2026-09-11 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('switch_provider', models.CharField(choices=[('mediswitch', 'MediSwitch'), ('healthbridge', 'Healthbridge'), ('medikredit', 'MediKredit'), ('manual', 'Manual Upload'), ('other', 'Other')], default='manual', max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='remittance_files/%Y/%m/')),
                ('received_date', models.DateField(auto_now_add=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('processed_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('raw_content', models.JSONField(blank=True, default=dict)),
                ('error_log', models.TextField(blank=True)),
                ('records_matched', models.IntegerField(default=0)),
                ('records_unmatched', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Remittance File',
                'verbose_name_plural': 'Remittance Files',
                'ordering': ['-received_date'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_number', models.CharField(max_length=20)),
                ('scheme_name', models.CharField(blank=True, max_length=255)),
                ('membership_number', models.CharField(max_length=50)),
                ('dependent_code', models.CharField(blank=True, max_length=5)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('date_of_service', models.DateField()),
                ('tariff_code', models.CharField(max_length=20)),
                ('amount_claimed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason_code', models.CharField(blank=True, max_length=20)),
                ('reason_description', models.CharField(blank=True, max_length=500)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('auto_matched', 'Auto Matched'), ('manual_matched', 'Manually Matched'), ('no_match', 'No Match Found')], default='unmatched', max_length=20)),
                ('matched_claim_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remittance_matches', to='claims.claimlineitem')),
                ('remittance_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reconciliation.remittancefile')),
            ],
            options={
                'verbose_name': 'Remittance Line',
                'verbose_name_plural': 'Remittance Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_method', models.CharField(choices=[('auto_exact', 'Automatic Exact Match'), ('auto_fuzzy', 'Automatic Fuzzy Match'), ('manual', 'Manual Match')], max_length=20)),
                ('match_confidence', models.IntegerField(default=0, help_text='0-100')),
                ('notes', models.TextField(blank=True)),
                ('claim_line_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='claims.claimlineitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('remittance_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='reconciliation.remittanceline')),
            ],
            options={
                'verbose_name': 'Reconciliation Log',
                'verbose_name_plural': 'Reconciliation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
