# Generated by Django 5.1 on 2026-09-14 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_alter_reconciliationlog_id_alter_remittancefile_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearinghouseConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='MediSwitch', max_length=100)),
                ('sftp_host', models.CharField(help_text='e.g. sftp.mediswitch.co.za', max_length=255)),
                ('sftp_port', models.IntegerField(default=22)),
                ('sftp_username', models.CharField(max_length=100)),
                ('sftp_password', models.CharField(blank=True, max_length=255)),
                ('bureau_bhf', models.CharField(blank=True, help_text='Your Bureau Practice Number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Clearinghouse Configuration',
                'verbose_name_plural': 'Clearinghouse Configurations',
            },
        ),
    ]
