# Generated by Django 6.1.1 on 2026-09-14 02:23

import django.db.models.deletion
import patients.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('id_number', patients.models.EncryptedCharField(blank=True, help_text='SA ID number', max_length=255)),
                ('phone', patients.models.EncryptedCharField(blank=True, max_length=255)),
                ('email', patients.models.EncryptedCharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=255)),
                ('next_of_kin_phone', patients.models.EncryptedCharField(blank=True, max_length=255)),
                ('alerts', models.TextField(blank=True, help_text='Clinical or administrative alerts')),
                ('consent_given', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='practices.practice')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('scheme_name', models.CharField(max_length=255)),
                ('scheme_option', models.CharField(blank=True, max_length=100)),
                ('membership_number', patients.models.EncryptedCharField(max_length=255)),
                ('dependent_code', models.CharField(default='00', max_length=5)),
                ('main_member_name', models.CharField(blank=True, max_length=255)),
                ('main_member_id_number', patients.models.EncryptedCharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='patients.patient')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='practices.practice')),
            ],
            options={
                'ordering': ['-is_active', 'scheme_name'],
            },
        ),
    ]
