# Generated by Django 5.1 on 2026-09-11 18:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(blank=True, help_text='SA ID number', max_length=13, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'Enter a valid 13-digit SA ID number.')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('physical_address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='practices.practice')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('practice', 'id_number')},
            },
        ),
        migrations.CreateModel(
            name='PatientScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme_name', models.CharField(max_length=255)),
                ('scheme_option', models.CharField(blank=True, max_length=100)),
                ('membership_number', models.CharField(max_length=50)),
                ('dependent_code', models.CharField(default='00', max_length=5)),
                ('main_member_name', models.CharField(blank=True, max_length=255)),
                ('main_member_id_number', models.CharField(blank=True, max_length=13)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Scheme',
                'verbose_name_plural': 'Patient Schemes',
                'ordering': ['-is_active', 'scheme_name'],
            },
        ),
    ]
