# Generated by Django 5.1 on 2026-09-12 07:07

import core.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=core.fields.EncryptedCharField(blank=True, help_text='SA ID number', max_length=255, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'Enter a valid 13-digit SA ID number.')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientscheme',
            name='main_member_id_number',
            field=core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientscheme',
            name='membership_number',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
    ]
