# Generated by Django 5.1 on 2026-09-11 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Billing Bureau', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='bureau_logos/')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, help_text='Percentage, e.g., 5.00 for 5%', max_digits=5)),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('contact_details', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Bureau Profile',
                'verbose_name_plural': 'Bureau Profiles',
            },
        ),
        migrations.CreateModel(
            name='PracticeInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_month', models.DateField(help_text='The month this invoice applies to (use the first day of the month)')),
                ('total_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='practices.practice')),
            ],
            options={
                'verbose_name': 'Practice Invoice',
                'verbose_name_plural': 'Practice Invoices',
                'ordering': ['-invoice_month', 'practice'],
            },
        ),
        migrations.CreateModel(
            name='PracticeInvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='bureau.practiceinvoice')),
            ],
            options={
                'verbose_name': 'Practice Invoice Line Item',
                'verbose_name_plural': 'Practice Invoice Line Items',
                'ordering': ['id'],
            },
        ),
    ]
