# Generated by Django 5.1 on 2026-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bureau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureauprofile',
            name='default_commission_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Percentage, e.g., 2.00 for 2%', max_digits=5),
        ),
    ]
